before_script:
  - "mysql -e 'create database lhm;'"
rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - gemfiles/ar-2.3.gemfile
  - gemfiles/ar-3.1.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/ar-2.3.gemfile
branches:
  only:
    - master
    - stable
